"""
自动文档生成器

基于代码分析结果自动生成文档，支持：
- 函数/方法文档
- 类/接口文档
- 模块文档
- 项目整体文档
- API 参考文档
- 调用关系图文档
"""

import os
from pathlib import Path
from typing import Optional, Dict, Any, List, Set, Tuple
from dataclasses import dataclass, field
from datetime import datetime

from loguru import logger

from ..parser.tree_sitter_parser import TreeSitterParser, Language
from ..parser.ast_extractor import ASTExtractor, CodeEntity, EntityType, Relation, RelationType
from ..indexer.knowledge_graph import KnowledgeGraph


@dataclass
class DocConfig:
    """文档生成配置"""
    output_format: str = "markdown"     # "markdown" | "html" | "rst"
    include_toc: bool = True
    include_call_graph: bool = True
    include_examples: bool = True
    include_complexity: bool = True
    language: str = "zh"               # "zh" | "en"
    template_dir: Optional[str] = None


class DocGenerator:
    """
    文档生成器

    基于解析和索引结果自动生成项目文档。

    使用示例:
        gen = DocGenerator(parser, extractor)
        doc = gen.generate_project_doc("/path/to/project", files)
        print(doc)

        # 生成单个文件文档
        doc = gen.generate_file_doc("src/main.py")

        # 生成 API 参考
        doc = gen.generate_api_reference(entities)
    """

    def __init__(
        self,
        parser: Optional[TreeSitterParser] = None,
        extractor: Optional[ASTExtractor] = None,
        knowledge_graph: Optional[KnowledgeGraph] = None,
        config: Optional[DocConfig] = None,
    ):
        """
        初始化文档生成器

        Args:
            parser: Tree-sitter 解析器
            extractor: AST 提取器
            knowledge_graph: 知识图谱（用于调用图等）
            config: 文档配置
        """
        self.parser = parser or TreeSitterParser()
        self.extractor = extractor or ASTExtractor()
        self.kg = knowledge_graph
        self.config = config or DocConfig()

    def generate_project_doc(
        self,
        project_root: str,
        files: List[str],
        title: str = "Project Documentation",
    ) -> str:
        """
        生成项目文档

        Args:
            project_root: 项目根目录
            files: 文件列表
            title: 文档标题

        Returns:
            生成的文档内容
        """
        parts = []

        # 标题
        parts.append(f"# {title}")
        parts.append(f"\n*Auto-generated by CodeLens AI on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*\n")

        # 项目概览
        parts.append("## Project Overview\n")
        parts.append(f"- **Project Root**: `{project_root}`")
        parts.append(f"- **Total Files**: {len(files)}")
        parts.append(f"- **Languages**: {self._detect_languages(files)}")

        # 目录结构
        parts.append("\n## Directory Structure\n")
        parts.append("```")
        parts.append(self._generate_directory_tree(project_root, files))
        parts.append("```")

        # 文件文档
        parts.append("\n## File Documentation\n")
        for file_path in sorted(files):
            rel_path = os.path.relpath(file_path, project_root)
            parts.append(self.generate_file_doc(file_path, heading_level=3))

        # 模块依赖图
        if self.kg and self.config.include_call_graph:
            parts.append("\n## Module Dependencies\n")
            parts.append(self._generate_dependency_section(files))

        return "\n".join(parts)

    def generate_file_doc(
        self,
        file_path: str,
        heading_level: int = 2,
    ) -> str:
        """
        生成文件文档

        Args:
            file_path: 文件路径
            heading_level: 标题级别

        Returns:
            文件文档
        """
        prefix = "#" * heading_level

        parts = []
        parts.append(f"{prefix} {os.path.basename(file_path)}")
        parts.append(f"\n**Path**: `{file_path}`\n")

        # 解析文件
        entities, relations = self.extractor.extract_from_file(file_path, self.parser)

        if not entities:
            parts.append("*No parsable entities found in this file.*\n")
            return "\n".join(parts)

        # 导入
        imports = [e for e in entities if e.type == EntityType.IMPORT]
        if imports:
            parts.append(f"{'#' * (heading_level + 1)} Imports\n")
            for imp in imports:
                parts.append(f"- `{imp.name}`")
            parts.append("")

        # 类
        classes = [e for e in entities if e.type == EntityType.CLASS]
        for cls in classes:
            parts.append(self._generate_class_doc(cls, heading_level + 1))

        # 函数
        functions = [e for e in entities if e.type in (EntityType.FUNCTION, EntityType.METHOD)]
        for func in functions:
            if func.type == EntityType.FUNCTION:  # 只处理顶层函数
                parts.append(self._generate_function_doc(func, heading_level + 1))

        # 统计
        if self.config.include_complexity:
            parts.append(f"{'#' * (heading_level + 1)} Statistics\n")
            parts.append(f"- Total entities: {len(entities)}")
            parts.append(f"- Functions: {len(functions)}")
            parts.append(f"- Classes: {len(classes)}")
            avg_complexity = sum(e.complexity for e in entities) / max(len(entities), 1)
            parts.append(f"- Average complexity: {avg_complexity:.1f}")
            parts.append("")

        return "\n".join(parts)

    def generate_api_reference(self, entities: List[CodeEntity]) -> str:
        """
        生成 API 参考文档

        Args:
            entities: 代码实体列表

        Returns:
            API 参考文档
        """
        parts = ["# API Reference\n"]

        # 按类型分组
        by_type: Dict[EntityType, List[CodeEntity]] = {}
        for entity in entities:
            by_type.setdefault(entity.type, []).append(entity)

        for entity_type, type_entities in by_type.items():
            parts.append(f"## {entity_type.value.title()}s\n")

            for entity in sorted(type_entities, key=lambda e: e.name):
                parts.append(f"### `{entity.name}`\n")

                if entity.signature:
                    parts.append(f"```\n{entity.signature}\n```\n")

                if entity.docstring:
                    parts.append(f"{entity.docstring}\n")

                if entity.parameters:
                    parts.append("**Parameters:**\n")
                    for param in entity.parameters:
                        param_type = f" ({param['type']})" if param.get('type') else ""
                        parts.append(f"- `{param['name']}`{param_type}")
                    parts.append("")

                if entity.return_type:
                    parts.append(f"**Returns:** `{entity.return_type}`\n")

                if self.config.include_complexity and entity.complexity > 0:
                    parts.append(f"**Complexity:** {entity.complexity}\n")

                parts.append(f"**Location:** `{entity.location}`\n")

                if entity.decorators:
                    parts.append(f"**Decorators:** {', '.join(f'`{d}`' for d in entity.decorators)}\n")

                parts.append("---\n")

        return "\n".join(parts)

    def generate_call_graph_doc(self, function_name: str) -> str:
        """
        生成调用图文档

        Args:
            function_name: 函数名称

        Returns:
            调用图文档
        """
        if self.kg is None:
            return "# Call Graph\n\n*Knowledge graph not available.*\n"

        parts = [f"# Call Graph: `{function_name}`\n"]

        callers = self.kg.get_callers(function_name)
        callees = self.kg.get_callees(function_name)

        # Mermaid 图
        parts.append("```mermaid")
        parts.append("graph TD")
        parts.append(f"    F[\"{function_name}\"]")

        for i, caller in enumerate(callers[:10]):
            safe_name = caller.name.replace(" ", "_").replace(".", "_")
            parts.append(f"    C{i}[\"{caller.name}\"] --> F")

        for i, callee in enumerate(callees[:10]):
            safe_name = callee.name.replace(" ", "_").replace(".", "_")
            parts.append(f"    F --> E{i}[\"{callee.name}\"]")
        parts.append("```\n")

        # 详细列表
        if callers:
            parts.append("## Called By\n")
            for caller in callers[:20]:
                parts.append(f"- `{caller.name}` ({caller.file_path}:{caller.start_line})")

        if callees:
            parts.append("\n## Calls\n")
            for callee in callees[:20]:
                parts.append(f"- `{callee.name}` ({callee.file_path}:{callee.start_line})")

        return "\n".join(parts)

    # ---- 内部方法 ----

    def _generate_class_doc(self, entity: CodeEntity, heading_level: int) -> str:
        """生成类文档"""
        prefix = "#" * heading_level
        parts = []

        parts.append(f"{prefix} class `{entity.name}`\n")

        if entity.base_classes:
            bases = ", ".join(f"`{b}`" for b in entity.base_classes)
            parts.append(f"**Inherits from:** {bases}\n")

        if entity.docstring:
            parts.append(f"{entity.docstring}\n")

        if entity.decorators:
            parts.append(f"**Decorators:** {', '.join(f'`{d}`' for d in entity.decorators)}\n")

        if self.config.include_complexity:
            parts.append(f"**Complexity:** {entity.complexity}\n")

        parts.append(f"**Location:** `{entity.location}`\n")

        return "\n".join(parts)

    def _generate_function_doc(self, entity: CodeEntity, heading_level: int) -> str:
        """生成函数文档"""
        prefix = "#" * heading_level
        parts = []

        modifier_str = " ".join(entity.modifiers) + " " if entity.modifiers else ""
        parts.append(f"{prefix} {modifier_str}`{entity.name}`\n")

        if entity.signature:
            parts.append(f"```\n{entity.signature}\n```\n")

        if entity.docstring:
            parts.append(f"{entity.docstring}\n")

        if entity.parameters:
            parts.append("**Parameters:**\n")
            for param in entity.parameters:
                param_type = f": `{param['type']}`" if param.get('type') else ""
                parts.append(f"- `{param['name']}`{param_type}")
            parts.append("")

        if entity.return_type:
            parts.append(f"**Returns:** `{entity.return_type}`\n")

        if entity.decorators:
            parts.append(f"**Decorators:** {', '.join(f'`{d}`' for d in entity.decorators)}\n")

        if self.config.include_complexity and entity.complexity > 0:
            parts.append(f"**Complexity:** {entity.complexity}\n")

        parts.append(f"**Location:** `{entity.location}`\n")

        return "\n".join(parts)

    def _generate_dependency_section(self, files: List[str]) -> str:
        """生成模块依赖部分"""
        parts = ["### Inter-Module Dependencies\n"]

        # 为每个模块生成被依赖的列表
        for file_path in sorted(files):
            summary = self.kg.get_module_summary(file_path)
            entities = summary.get("functions", []) + summary.get("classes", [])
            if entities:
                parts.append(f"\n**{os.path.basename(file_path)}** ({len(entities)} entities):")
                for entity_name in entities[:10]:
                    dependents = self.kg.get_dependents(entity_name)
                    if dependents:
                        dep_names = [d.name for d in dependents[:5]]
                        parts.append(f"  - `{entity_name}` is used by: {', '.join(f'`{n}`' for n in dep_names)}")

        return "\n".join(parts)

    def _generate_directory_tree(self, root: str, files: List[str]) -> str:
        """生成目录树"""
        root_path = Path(root)

        tree = {}
        for f in files:
            try:
                rel = Path(f).relative_to(root_path)
            except ValueError:
                rel = Path(f)
            parts = rel.parts
            current = tree
            for part in parts[:-1]:
                current = current.setdefault(part, {})
            current[parts[-1]] = None  # 叶子节点

        def render(node: Dict, prefix: str = "", is_last: bool = True) -> List[str]:
            lines = []
            items = list(node.items())
            for i, (name, children) in enumerate(items):
                is_item_last = (i == len(items) - 1)
                connector = "└── " if is_item_last else "├── "
                lines.append(prefix + connector + name)
                if children is not None:
                    ext_prefix = "    " if is_item_last else "│   "
                    lines.extend(render(children, prefix + ext_prefix, is_item_last))
            return lines

        root_name = root_path.name or root_path.absolute().name
        lines = [root_name]
        lines.extend(render(tree))
        return "\n".join(lines)

    def _detect_languages(self, files: List[str]) -> str:
        """检测项目中使用的语言"""
        languages: Set[str] = set()
        for f in files:
            lang = Language.from_filename(f)
            if lang != Language.UNKNOWN:
                languages.add(lang.value)
        return ", ".join(sorted(languages)) if languages else "Unknown"

    def save_doc(self, content: str, output_path: str):
        """保存文档到文件"""
        Path(output_path).write_text(content, encoding="utf-8")
        logger.info(f"文档已保存到: {output_path}")

    def generate_and_save(
        self,
        project_root: str,
        files: List[str],
        output_path: str = "./docs/PROJECT_DOCUMENTATION.md",
    ) -> str:
        """生成文档并保存"""
        doc = self.generate_project_doc(project_root, files)
        self.save_doc(doc, output_path)
        return doc
